extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:

  hostmetrics:
    scrape_interval: 1s
    cpu:
      reportpercpu: true
      reportperprocess: true

exporters:

  logging:

  prometheus:
    endpoint: "0.0.0.0:8889"

service:

  pipelines:

    metrics:
      receivers: [hostmetrics]
      exporters: [logging, prometheus]

  extensions: [health_check, pprof, zpages]
